### ISSUE TITLE
Keep entered email when registration info is invalid

### ISSUE THREAD

**Issue by razzius** [stormpath/stormpath-flask-sample#2]
This isn't a necessity, but keeping the email the user entered in the form when it is re-rendered would be a nice feature. It's something I intend to implement for my own app, and I'm not sure about the best way to go about it.

![screen shot 2014-05-07 at 1 24 46 pm](https://cloud.githubusercontent.com/assets/2244895/2906147/7e14000e-d60d-11e3-8d4a-246b111d16b0.png)

**Comment by asciifaceman** [comment]
Hey I just wanted to say you can repopulate forms with WTForms and could for awhile now, you just have to send the form object back to the page iirc
