### ISSUE TITLE
How to enable the email verification in flask?

### ISSUE THREAD

**Issue by tim-hub** [stormpath/stormpath-flask-sample#8]
It said it is easily. ![](https://github.com/stormpath/stormpath-flask-sample/blob/master/assets/registration-page.png?raw=true)

But how to config it?

Thanks

**Comment by rdegges** [comment]
The library doesn't support it natively (yet), so you have to use the underlying Python library manually. See: https://docs.stormpath.com/python/product-guide/latest/accnt_mgmt.html#how-to-verify-an-account-s-email
